name: tyk

services:

  tyk:
    build: .
    ports:
      - 443:8080
    mem_reservation: 512M
    environment:
      - TYK_GW_APPPATH=${APP_PATH}

  redis:
    image: redis:latest
    mem_reservation: 512M
